using System.ComponentModel.DataAnnotations.Schema;

namespace LoggingAPI.PostgresDb.Models;

/// <summary>
/// Application model in data access object format.
/// </summary>
[Table("application")]
public class Application
{
    public Application()
    {
        LogMessages = new HashSet<LogMessage>();
    }

    /// <summary>
    /// Auto-generated by database application's ID.
    /// </summary>
    [Column("id")]
    public int Id { get; set; }

    /// <summary>
    /// Application's name agreed witn API's clients.
    /// </summary>
    [Column("name")]
    public string? Name { get; set; }

    /// <summary>
    /// Log messages logged by this application.
    /// </summary>
    public virtual ICollection<LogMessage> LogMessages { get; set; }
}
