using LoggingAPI.Models;
using System.ComponentModel.DataAnnotations.Schema;

namespace LoggingAPI.PostgresDb.Models;

/// <summary>
/// Log message model in data access object format.
/// </summary>
[Table("logmessage")]
public class LogMessage
{
    /// <summary>
    /// Auto-generated by database log messages's ID.
    /// </summary>
    [Column("id")]
    public int Id { get; set; }

    /// <summary>
    /// ID of the application, which logged the message.
    /// </summary>
    [Column("application_id")]
    public int ApplicationId { get; set; }

    /// <summary>
    /// Date and time of the message creation with timezone specified.
    /// </summary>
    [Column("date")]
    public DateTimeOffset? Date { get; set; }

    /// <summary>
    /// The text of the message.
    /// </summary>
    [Column("message")]
    public string? Message { get; set; }

    /// <summary>
    /// Log level of the message.
    /// </summary>
    [Column("log_level")]
    public LogLevel? LogLevel { get; set; }

    /// <summary>
    /// Application, which logged the message.
    /// </summary>
    public virtual Application Application { get; set; } = null!;
}
